package sandbox

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Language identifies a supported runtime.
type Language string

const (
	// Orva offers exactly two runtimes, latest-stable only: `node` (Node.js 24)
	// and `python` (Python 3.14). The identifier is generic on purpose — the
	// concrete version is an implementation detail that tracks latest-stable and
	// is surfaced only as a display label (see handlers/runtimes.go). Legacy
	// versioned IDs (node22/node24/python313/python314) are rewritten to these
	// at startup — see migrations.go.
	Node   Language = "node"
	Python Language = "python"
)

// IsNode reports whether a language is the Node runtime.
func (l Language) IsNode() bool { return l == Node }

// IsPython reports whether a language is the Python runtime.
func (l Language) IsPython() bool { return l == Python }

// ExecConfig holds everything needed to run user code in nsjail.
type ExecConfig struct {
	Language Language
	CodeDir  string // Directory containing user code
	Stdin    []byte // Request JSON piped to stdin
	Timeout  time.Duration
	MemoryMB int
	MaxPids  int
	MaxCPUs  float64 // 0 = no cpu cap; positive = fractional CPUs allowed (e.g. 0.5)

	// Env holds environment variables injected into the sandbox. Includes
	// both function config env_vars and decrypted secrets at invoke time.
	Env map[string]string

	// Seccomp policy (Kafel string). Empty means no seccomp filter.
	SeccompPolicy string

	// NetworkMode controls the sandbox's network access. "" or "none"
	// keeps the function in an isolated net namespace with only loopback
	// (the safe default — blocks egress and exfil). "egress" adds nsjail's
	// --user_net flag, which gives the sandbox a userspace TCP/UDP stack
	// (the bundled "nstun" backend) that NATs out via the host without
	// exposing host interfaces, filtered by the compiled egress policy.
	NetworkMode string

	// ResolvConfPath, when non-empty AND NetworkMode=="egress", is the
	// path of an operator-managed resolv.conf bind-mounted into the
	// sandbox at /etc/resolv.conf. Generated by the firewall manager
	// from system_config.dns_servers. Empty falls back to whatever the
	// rootfs ships (usually nothing meaningful for slim images).
	ResolvConfPath string

	// HostsPath, when non-empty AND NetworkMode=="egress", is bind-mounted
	// at /etc/hosts so operator-defined host→IP overrides take precedence
	// over upstream DNS. Generated by the firewall manager from
	// system_config.dns_records.
	HostsPath string

	// EgressPolicyPath is the nsjail --config file holding the compiled NSTUN
	// user_net rules. REQUIRED when NetworkMode=="egress": an empty path is a
	// spawn error, never a silent fall-through.
	//
	// This deliberately does NOT follow the skip-if-missing posture used for
	// ResolvConfPath/HostsPath above. Missing DNS config degrades a sandbox;
	// missing egress policy would run it completely unfiltered, because NSTUN
	// allows anything no rule matches.
	EgressPolicyPath string

	// EgressPolicyGen identifies the policy generation, for logs and metrics.
	EgressPolicyGen string

	// Paths (populated from config at startup).
	NsjailBin string
	RootfsDir string // e.g. ~/.orva/rootfs
}

// ErrEgressPolicyMissing means an egress sandbox was asked to start without a
// compiled policy. This is fail-closed by design: NSTUN allows any destination
// no rule matches, so spawning without a policy would run the function with no
// filtering at all — strictly worse than not running it.
var ErrEgressPolicyMissing = errors.New("egress policy config missing: refusing to start an unfiltered sandbox")

// ExecResult holds the outcome of a sandboxed execution.
type ExecResult struct {
	Stdout   []byte
	Stderr   []byte
	ExitCode int
	Duration time.Duration
	TimedOut bool
	Error    error
}

// Execute runs user code inside an nsjail sandbox. Each call spawns a
// fresh process — no daemon, no pool.
func Execute(ctx context.Context, cfg ExecConfig) *ExecResult {
	start := time.Now()
	cfg = applyExecDefaults(cfg)

	rootfs, entrypoint, err := resolveRuntime(cfg)
	if err != nil {
		return &ExecResult{Error: err, Duration: time.Since(start)}
	}

	args, err := buildArgs(cfg, rootfs, entrypoint)
	if err != nil {
		return &ExecResult{Error: err, Duration: time.Since(start)}
	}

	ctx, cancel := context.WithTimeout(ctx, cfg.Timeout+5*time.Second)
	defer cancel()

	// nsjail itself carries the required capabilities via setcap (installed
	// by `orva setup` or baked into the Docker image). No sudo wrapper.
	cmd := exec.CommandContext(ctx, cfg.NsjailBin, args...)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	if len(cfg.Stdin) > 0 {
		cmd.Stdin = bytes.NewReader(cfg.Stdin)
	}

	err = cmd.Run()

	result := &ExecResult{
		Stdout:   stdout.Bytes(),
		Stderr:   stderr.Bytes(),
		Duration: time.Since(start),
	}

	if err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			result.ExitCode = exitErr.ExitCode()
		} else {
			result.Error = err
		}
		if ctx.Err() == context.DeadlineExceeded {
			result.TimedOut = true
		}
	}

	return result
}

// applyExecDefaults is shared by one-shot execution and pooled workers.
// Keeping the defaults in one place is security-sensitive: passing MaxPids=0
// to nsjail's cgroup-v2 flag means "allow zero processes", so every pooled
// worker exits immediately on hosts where cgroup delegation is available.
func applyExecDefaults(cfg ExecConfig) ExecConfig {
	if cfg.Timeout == 0 {
		cfg.Timeout = 30 * time.Second
	}
	if cfg.MemoryMB == 0 {
		cfg.MemoryMB = 64
	}
	if cfg.MaxPids == 0 {
		cfg.MaxPids = 32
	}
	return cfg
}

func resolveRuntime(cfg ExecConfig) (rootfs, entrypoint string, err error) {
	adapter := ""
	switch cfg.Language {
	case Python:
		rootfs = filepath.Join(cfg.RootfsDir, string(cfg.Language))
		entrypoint = "/usr/local/bin/python3"
		adapter = "/opt/orva/adapter.py"
	case Node:
		rootfs = filepath.Join(cfg.RootfsDir, string(cfg.Language))
		entrypoint = "/usr/local/bin/node"
		adapter = "/opt/orva/adapter.js"
	default:
		return "", "", fmt.Errorf("unsupported language: %s", cfg.Language)
	}

	rootInfo, err := os.Stat(rootfs)
	if err != nil {
		return "", "", fmt.Errorf("rootfs not found at %s: %w", rootfs, err)
	}
	if !rootInfo.IsDir() {
		return "", "", fmt.Errorf("rootfs path is not a directory: %s", rootfs)
	}
	entrypointPath := filepath.Join(rootfs, filepath.FromSlash(strings.TrimPrefix(entrypoint, "/")))
	entrypointInfo, err := os.Stat(entrypointPath)
	if err != nil || entrypointInfo.IsDir() || entrypointInfo.Mode()&0o111 == 0 {
		return "", "", fmt.Errorf("runtime entrypoint is missing or not executable at %s", entrypointPath)
	}
	adapterPath := filepath.Join(rootfs, filepath.FromSlash(strings.TrimPrefix(adapter, "/")))
	adapterInfo, err := os.Stat(adapterPath)
	if err != nil || adapterInfo.IsDir() {
		return "", "", fmt.Errorf("runtime adapter is missing at %s", adapterPath)
	}
	return rootfs, entrypoint, nil
}

func buildArgs(cfg ExecConfig, rootfs, entrypoint string) ([]string, error) {
	// Prefer user namespaces for nsjail's mount/chroot setup. On hosts that
	// restrict unprivileged user namespaces, the bare-metal installer grants
	// the nsjail executable the narrow capability set it needs and exports
	// ORVA_DISABLE_USERNS=1. Docker keeps the default userns path.
	//
	// NOTE: --time_limit intentionally dropped; Go-side context.WithTimeout
	// + Worker.Kill() handles timeouts with millisecond resolution and
	// avoids the skew from nsjail's whole-second limit.
	var args []string

	// The compiled egress policy is loaded via --config, which MUST be the very
	// first argument — see egressConfigArgs for why, and for the fail-closed
	// contract when no policy is available.
	prefix, err := egressConfigArgs(cfg.NetworkMode, cfg.EgressPolicyPath)
	if err != nil {
		return nil, err
	}
	args = append(args, prefix...)

	args = append(args,
		"-Mo",
		"--chroot", rootfs,
		"-R", cfg.CodeDir+":/code",
		"-T", "/tmp",
		"--rlimit_as", "max",
		// -q (WARNING), not -Q (FATAL): nsjail gates rule-compilation errors
		// behind ERROR, so -Q made every malformed-policy diagnostic invisible.
		// NSTUN is default-allow, so a silently dropped rule is a security
		// failure we must be able to see.
		"-q",
	)
	if os.Getenv("ORVA_DISABLE_USERNS") == "1" {
		args = append(args, "--disable_clone_newuser")
	}

	// Per-function egress. Functions that don't need network access stay
	// loopback-only — that's the safe default and blocks data exfiltration
	// from compromised handlers.
	args = append(args, egressNetArgs(cfg.NetworkMode, cfg.ResolvConfPath, cfg.HostsPath)...)

	// Cgroup v2 resource limits — only enabled if we have a writable cgroup
	// delegate (systemd user slice on most modern hosts; bind-mounted in the
	// Docker image). Without delegation nsjail can't create the NSJAIL.<pid>
	// cgroup, so rather than crashing we silently drop the memory/pid caps.
	// The process-level rlimit_as flag above still bounds address-space.
	if mount := cgroupv2Delegate(); mount != "" {
		// cgroup v2 memory.max at 1.5× the declared memory. This gives the
		// kernel headroom to reclaim via PSI pressure before OOM-killing,
		// and matches the 1.5× per-worker budget the autoscaler uses for
		// admission control.
		memMaxBytes := int64(cfg.MemoryMB) * 1024 * 1024 * 3 / 2
		args = append(args,
			"--use_cgroupv2",
			"--cgroupv2_mount", mount,
			"--cgroup_mem_max", fmt.Sprintf("%d", memMaxBytes),
			"--cgroup_pids_max", fmt.Sprintf("%d", cfg.MaxPids),
		)
		// Use cgroup CPU bandwidth (cpu.max) instead of --max_cpus. The
		// --max_cpus flag is an affinity mask that pins the process to a
		// subset of cores — actively harmful under concurrency because the
		// kernel can't load-balance across the full CPU set. Bandwidth
		// limits (microseconds per period) are what fractional CPU means.
		if msPerSec := int(cfg.MaxCPUs * 1000); msPerSec > 0 {
			// nsjail --cgroup_cpu_ms_per_sec = ms of CPU per 1000 ms window.
			// Supports fractional CPUs: 0.5 → 500, 0.25 → 250.
			args = append(args,
				"--cgroup_cpu_ms_per_sec",
				fmt.Sprintf("%d", msPerSec),
			)
		}
	}

	if cfg.SeccompPolicy != "" {
		args = append(args, "--seccomp_string", cfg.SeccompPolicy)
	}

	// Inject env vars + secrets. nsjail takes --env KEY=VAL; an --env with
	// no '=' passes the host-side value through, which we never want for
	// security. Always format as KEY=VAL explicitly.
	for k, v := range cfg.Env {
		if k == "" {
			continue
		}
		args = append(args, "--env", k+"="+v)
	}
	// Also tell the Python/Node adapter about Orva context via env.
	args = append(args,
		"--env", "ORVA_FUNCTION_ID="+getenvOr(cfg.Env, "ORVA_FUNCTION_ID", ""),
		"--env", "ORVA_EXECUTION_ID="+getenvOr(cfg.Env, "ORVA_EXECUTION_ID", ""),
	)

	args = append(args, "--", entrypoint)

	switch {
	case cfg.Language.IsPython():
		args = append(args, "/opt/orva/adapter.py")
	case cfg.Language.IsNode():
		args = append(args, "/opt/orva/adapter.js")
	}

	return args, nil
}

// egressConfigArgs returns the `--config <policy>` prefix an egress jail must
// carry, or an error when no usable policy exists. Shared by the worker jail
// (buildArgs) and the build jail (buildJailArgs) so there is exactly one
// fail-closed implementation: NSTUN allows every destination no rule matches,
// so starting either one without a policy would run it entirely unfiltered.
//
// The caller must place the returned args FIRST. nsjail's config loader does a
// CopyFrom onto the config message, and CopyFrom CLEARS the destination first —
// so every njc-backed flag parsed before it is silently destroyed, including
// --env (i.e. every secret and ORVA_API_BASE), --seccomp_string, --cwd, the
// --cgroup_* and --rlimit_* flags, and all bind mounts. Flags parsed AFTER it
// survive and take precedence, which is what we want. Verified empirically: an
// --env before --config arrives empty in the jail, and a --cwd before it is
// silently reset to "/".
//
// There is no CLI flag for NSTUN rules, so a config file is the only way to
// express policy at all.
func egressConfigArgs(mode, policyPath string) ([]string, error) {
	if mode != "egress" {
		return nil, nil
	}
	if policyPath == "" {
		return nil, ErrEgressPolicyMissing
	}
	// Confirm the generation file is still on disk. Without this the failure
	// still fails closed — nsjail exits 255 on an unreadable --config — but it
	// surfaces as a generic crash with an operator hint pointing at the wrong
	// thing. Catching it here maps both variants (no policy compiled, and a
	// compiled policy whose file has gone missing) onto one actionable error.
	if _, err := os.Stat(policyPath); err != nil {
		return nil, fmt.Errorf("%w: %s", ErrEgressPolicyMissing, policyPath)
	}
	return []string{"--config", policyPath}, nil
}

// egressNetArgs returns the network flags for an egress jail: nsjail's default
// already creates a fresh net namespace with only loopback; --user_net layers a
// userspace TCP/UDP stack (nsjail's bundled "nstun" backend) on top so the jail
// can reach external hosts without ever touching a host interface. Requires
// /dev/net/tun in the container; the entrypoint mknods it on startup.
//
// The DNS files are bind-mounted read-only over the chroot's own so name
// resolution matches what the operator configured. Both are skipped silently
// when absent — the firewall manager writes them on its first refresh tick, so
// a fresh boot may briefly fall back to whatever the rootfs ships. /etc/hosts
// beats upstream DNS because the resolver consults files first.
func egressNetArgs(mode, resolvConfPath, hostsPath string) []string {
	if mode != "egress" {
		return nil
	}
	args := []string{"--user_net"}
	for _, m := range []struct{ src, dst string }{
		{resolvConfPath, "/etc/resolv.conf"},
		{hostsPath, "/etc/hosts"},
	} {
		if m.src == "" {
			continue
		}
		if _, err := os.Stat(m.src); err != nil {
			continue
		}
		args = append(args, "-R", m.src+":"+m.dst)
	}
	return args
}

var (
	cgroupOnce  sync.Once
	cgroupMount string
)

// cgroupv2Delegate returns a cgroup v2 path this process can create children
// under, or "" if no suitable delegate exists. Detects the cgroup from
// /proc/self/cgroup and walks up until it finds a writable directory.
// An explicit override via ORVA_CGROUPV2_MOUNT takes precedence.
func cgroupv2Delegate() string {
	cgroupOnce.Do(func() {
		if v := os.Getenv("ORVA_CGROUPV2_MOUNT"); v != "" {
			if _, err := os.Stat(v); err == nil {
				cgroupMount = v
			}
			return
		}

		data, err := os.ReadFile("/proc/self/cgroup")
		if err != nil {
			return
		}
		// cgroup v2 line: "0::/user.slice/...".
		var rel string
		for _, line := range strings.Split(string(data), "\n") {
			parts := strings.SplitN(line, ":", 3)
			if len(parts) == 3 && parts[0] == "0" && parts[1] == "" {
				rel = parts[2]
				break
			}
		}
		if rel == "" {
			return
		}
		// Walk up from the current cgroup until we find a writable dir that
		// actually has the controllers we need delegated to children.
		p := filepath.Join("/sys/fs/cgroup", rel)
		for p != "/sys/fs/cgroup" && p != "/" {
			if isWritableDir(p) {
				cgroupMount = p
				return
			}
			p = filepath.Dir(p)
		}
	})
	if cgroupMount == "" {
		// One-time heads-up: no usable cgroup-v2 delegate, so per-sandbox
		// memory/pid/cpu caps are NOT enforced (we fall back to rlimits). This
		// is normal on hosts where systemd doesn't delegate controllers to the
		// service (e.g. constrained VMs/containers); functions still run fully
		// isolated via nsjail. Set Delegate=yes + delegate the controllers, or
		// ORVA_CGROUPV2_MOUNT, to enable hard caps.
		cgroupWarnOnce.Do(func() {
			slog.Warn("cgroup v2 controllers not delegated; per-sandbox memory/pid/cpu caps disabled (rlimit-only fallback)")
		})
	}
	return cgroupMount
}

var cgroupWarnOnce sync.Once

func getenvOr(m map[string]string, k, def string) string {
	if v, ok := m[k]; ok {
		return v
	}
	return def
}

// cgroupNeededControllers are the controllers nsjail writes into the sandbox's
// child cgroup (memory.max / pids.max / cpu.max). They only appear in a child
// when the parent delegates them via cgroup.subtree_control.
var cgroupNeededControllers = []string{"memory", "pids", "cpu"}

func isWritableDir(p string) bool {
	// cgroupfs does not allow creating regular files — probe by creating a
	// child cgroup directory and checking the kernel auto-creates cgroup.procs.
	probe := filepath.Join(p, ".orva-cg-probe")
	if err := os.Mkdir(probe, 0o755); err != nil {
		return false
	}
	defer os.Remove(probe)
	if _, err := os.Stat(filepath.Join(probe, "cgroup.procs")); err != nil {
		return false
	}
	// Being able to mkdir a child is NOT enough: nsjail will write memory.max /
	// pids.max / cpu.max into its own child cgroup, and those knobs exist only
	// when the parent delegated the controllers (cgroup.subtree_control). On
	// hosts where the controllers aren't delegated to children — e.g. the
	// cgroup-v2 "no internal processes" rule blocks it because the server
	// process sits directly in this cgroup — the child exposes no controllers,
	// nsjail's cgroup write fails, and every worker crashes. Verify the child
	// actually carries the controllers we need; if not, report no-delegate so
	// the caller falls back to rlimit-only (functions run, just without the
	// per-sandbox cgroup memory/pid caps) instead of crashing.
	return childHasControllers(probe)
}

// childHasControllers reports whether a freshly-created child cgroup exposes all
// the controllers Orva's sandbox needs.
func childHasControllers(child string) bool {
	data, err := os.ReadFile(filepath.Join(child, "cgroup.controllers"))
	if err != nil {
		return false
	}
	have := make(map[string]bool)
	for _, c := range strings.Fields(string(data)) {
		have[c] = true
	}
	for _, need := range cgroupNeededControllers {
		if !have[need] {
			return false
		}
	}
	return true
}

// CgroupV2Mount returns the cgroup v2 path nsjail cgroups are created under,
// or "" if no suitable delegate exists.
func CgroupV2Mount() string { return cgroupv2Delegate() }

// FindJailedCgroupPath locates the NSJAIL.* cgroup that nsjail created for
// its jailed child process. nsjail names the cgroup after the CHILD's PID
// (the Python/Node adapter process), not nsjail's own PID, so we search for
// a NSJAIL.* cgroup whose cgroup.procs contains a process whose parent is
// nsjailPid. Returns "" if not found within 500ms.
func FindJailedCgroupPath(mount string, nsjailPid int) string {
	if mount == "" || nsjailPid <= 0 {
		return ""
	}
	deadline := time.Now().Add(500 * time.Millisecond)
	for time.Now().Before(deadline) {
		entries, err := os.ReadDir(mount)
		if err != nil {
			return ""
		}
		for _, e := range entries {
			if !strings.HasPrefix(e.Name(), "NSJAIL.") {
				continue
			}
			cgPath := filepath.Join(mount, e.Name())
			data, err := os.ReadFile(filepath.Join(cgPath, "cgroup.procs"))
			if err != nil {
				continue
			}
			for _, pidStr := range strings.Fields(string(data)) {
				pid, err := strconv.Atoi(strings.TrimSpace(pidStr))
				if err != nil || pid <= 0 {
					continue
				}
				if procPPID(pid) == nsjailPid {
					return cgPath
				}
			}
		}
		time.Sleep(10 * time.Millisecond)
	}
	return ""
}

// procPPID returns the parent PID of the given process by reading /proc/pid/stat.
func procPPID(pid int) int {
	data, err := os.ReadFile(fmt.Sprintf("/proc/%d/stat", pid))
	if err != nil {
		return 0
	}
	// Format: pid (comm) state ppid ...  — find ppid after the closing ')'
	s := string(data)
	if i := strings.LastIndex(s, ") "); i >= 0 {
		fields := strings.Fields(s[i+2:])
		if len(fields) >= 2 {
			ppid, _ := strconv.Atoi(fields[1])
			return ppid
		}
	}
	return 0
}

// ReadCgroupMemCurrent reads memory.current from a cgroup v2 directory.
// Returns 0 on any error (cgroup not yet created, not mounted, etc.).
func ReadCgroupMemCurrent(cgPath string) int64 {
	if cgPath == "" {
		return 0
	}
	data, err := os.ReadFile(filepath.Join(cgPath, "memory.current"))
	if err != nil {
		return 0
	}
	v, _ := strconv.ParseInt(strings.TrimSpace(string(data)), 10, 64)
	return v
}

// ReadCgroupCPUUsec reads the cumulative usage_usec from cpu.stat in a
// cgroup v2 directory. Returns 0 on any error.
func ReadCgroupCPUUsec(cgPath string) int64 {
	if cgPath == "" {
		return 0
	}
	data, err := os.ReadFile(filepath.Join(cgPath, "cpu.stat"))
	if err != nil {
		return 0
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "usage_usec ") {
			v, _ := strconv.ParseInt(strings.TrimPrefix(line, "usage_usec "), 10, 64)
			return v
		}
	}
	return 0
}
