#!/bin/sh
# Orva container entrypoint.
#
# The rootfs + adapters are baked into the image. When users mount a volume
# at /var/lib/orva to persist their DB + function code, that volume shadows
# the image's /var/lib/orva/rootfs. On first start the volume is empty and
# we copy the rootfs in. On upgrades we refresh the adapters in case the
# image has newer versions.

set -e

IMAGE_ROOTFS=/opt/orva/rootfs
VOLUME_ROOTFS=/var/lib/orva/rootfs

RUNTIMES="node python"

for rt in $RUNTIMES; do
  # If the volume's rootfs for this runtime is empty, seed it from the image.
  if [ ! -d "$VOLUME_ROOTFS/$rt/usr" ]; then
    echo ">> seeding $VOLUME_ROOTFS/$rt from image"
    mkdir -p "$VOLUME_ROOTFS/$rt"
    cp -a "$IMAGE_ROOTFS/$rt/." "$VOLUME_ROOTFS/$rt/"
  fi
done

# Always refresh the adapters + bundled SDK so image upgrades roll out
# even when the user has an existing volume. Includes the orva module
# (kv / invoke / jobs) introduced in v0.2.
rt=node
mkdir -p "$VOLUME_ROOTFS/$rt/opt/orva"
cp "$IMAGE_ROOTFS/$rt/opt/orva/adapter.js" "$VOLUME_ROOTFS/$rt/opt/orva/adapter.js"
if [ -d "$IMAGE_ROOTFS/$rt/opt/orva/node_modules/orva" ]; then
  # Replace rather than merge: older images shipped orva.js under the name
  # index.js, and a merge would leave that stale copy in the volume forever.
  rm -rf "$VOLUME_ROOTFS/$rt/opt/orva/node_modules/orva"
  mkdir -p "$VOLUME_ROOTFS/$rt/opt/orva/node_modules/orva"
  cp -a "$IMAGE_ROOTFS/$rt/opt/orva/node_modules/orva/." "$VOLUME_ROOTFS/$rt/opt/orva/node_modules/orva/"
fi
rt=python
mkdir -p "$VOLUME_ROOTFS/$rt/opt/orva"
cp "$IMAGE_ROOTFS/$rt/opt/orva/adapter.py" "$VOLUME_ROOTFS/$rt/opt/orva/adapter.py"
if [ -f "$IMAGE_ROOTFS/$rt/opt/orva/orva.py" ]; then
  cp "$IMAGE_ROOTFS/$rt/opt/orva/orva.py" "$VOLUME_ROOTFS/$rt/opt/orva/orva.py"
fi
if [ -f "$IMAGE_ROOTFS/$rt/opt/orva/py.typed" ]; then
  cp "$IMAGE_ROOTFS/$rt/opt/orva/py.typed" "$VOLUME_ROOTFS/$rt/opt/orva/py.typed"
fi

mkdir -p /var/lib/orva/functions

# /dev/net/tun is required by nsjail's --user_net (nstun backend) which
# powers the per-function egress toggle. Containers don't get it by
# default; mknod it here so functions with network_mode=egress can spin
# up their userspace TCP/UDP stack. Failure is non-fatal — only egress
# functions need it, and operators may have already provided the device
# via `docker run --device /dev/net/tun`.
if [ ! -e /dev/net/tun ]; then
  mkdir -p /dev/net 2>/dev/null || true
  if mknod /dev/net/tun c 10 200 2>/dev/null; then
    chmod 0666 /dev/net/tun
    echo ">> created /dev/net/tun for egress sandboxes"
  else
    echo ">> WARN: could not create /dev/net/tun — egress functions will fail to spawn"
    echo "         (re-run docker with --device /dev/net/tun if you need egress)"
  fi
fi

touch /var/lib/orva/.setup-complete

# The daemon prepares its own daemon/worker leaves inside this container's
# cgroup. Move only the known tini supervisor into a sibling leaf first:
# cgroup-v2 domain controllers cannot be enabled while tini shares the parent
# with the daemon. Never create a group at the host cgroup root.
SUPERVISOR_CGROUP=
if [ "${1:-}" = /usr/local/bin/orva ] && [ "${2:-}" = serve ] &&
   [ -r /proc/self/cgroup ] && [ "$(cat "/proc/$PPID/comm" 2>/dev/null)" = tini ]; then
  cgroup_rel=$(sed -n 's/^0:://p' /proc/self/cgroup)
  case "$cgroup_rel" in
    /*) if [ "$cgroup_rel" != / ]; then
          cgroup_base=/sys/fs/cgroup$cgroup_rel
          if mkdir "$cgroup_base/orva.supervisor" 2>/dev/null &&
             printf '%s\n' "$PPID" > "$cgroup_base/orva.supervisor/cgroup.procs" 2>/dev/null; then
            SUPERVISOR_CGROUP=$cgroup_base/orva.supervisor
          fi
        fi ;;
  esac
fi

# Pre-configure the in-container CLI so `docker exec orva orva functions list`
# works without the operator hunting for the bootstrap key.
#
# The binary at /usr/local/bin/orva serves both roles: `orva serve` is the
# daemon, every other subcommand is the CLI client. The CLI reads
# ~/.orva/config.yaml for endpoint + api_key. We can't write it here
# synchronously because the bootstrap key is generated by orvad after it
# starts. Instead, kick off a background helper that polls for the
# keyfile and writes the config the first time it appears.
#
# Trust note: the keyfile and the resulting config.yaml both live on the
# container filesystem owned by root inside the container — same trust
# boundary as SQLite. Any process that can already read /var/lib/orva
# can already read this file.
write_cli_config() (
    keyfile=/var/lib/orva/.admin-key
    cfg_dir=/root/.orva
    cfg_path="$cfg_dir/config.yaml"

    # Wait up to 60s for orvad to write the bootstrap keyfile.
    i=0
    while [ ! -s "$keyfile" ] && [ "$i" -lt 60 ]; do
        sleep 1
        i=$((i + 1))
    done
    [ -s "$keyfile" ] || { echo ">> WARN: bootstrap key not seen within 60s; CLI config not written" >&2; return; }

    api_key=$(tr -d '[:space:]' < "$keyfile")
    [ -n "$api_key" ] || return

    mkdir -p "$cfg_dir"
    chmod 700 "$cfg_dir"
    # Recreate every boot — the key may have rotated and the daemon may
    # have moved (port change). Idempotent and cheap.
    umask 077
    cat > "$cfg_path" <<EOF
endpoint: http://localhost:8443
api_key: $api_key
EOF
    echo ">> wrote CLI config to $cfg_path (endpoint=http://localhost:8443)"
)
write_cli_config &
cli_helper_pid=$!
if [ -n "$SUPERVISOR_CGROUP" ]; then
  # The helper belongs to this entrypoint and may finish before the move.
  printf '%s\n' "$cli_helper_pid" > "$SUPERVISOR_CGROUP/cgroup.procs" 2>/dev/null || true
fi

exec "$@"
