#!/usr/bin/env python3
"""
run.py — orchestrator for Orva's comprehensive E2E suite.

Default: build a fresh local Docker image, run an ISOLATED container, run every
test module against it, write CHECKLIST.md, and tear down. Nothing touches the
dev instance.

Usage:
  python3 run.py                 # isolated Docker run (build if needed)
  python3 run.py --rebuild       # force-rebuild the image first
  python3 run.py --keep          # leave the container running after the run
  python3 run.py --filter cli    # only modules whose name contains "cli"
  python3 run.py --url URL --api-key KEY   # run against an existing instance
                                            # (no Docker) — e.g. the host service

Each test module is a standalone script printing a machine-readable trailer
"RESULT pass=<n> fail=<m> [skip=1]"; run.py aggregates these into CHECKLIST.md.
"""
import argparse
import datetime
import glob
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TESTS_DIR = os.path.join(HERE, "tests")
RESULT_RE = re.compile(r"^RESULT pass=(\d+) fail=(\d+)(?: skip=(\d+))?$")
ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")


def discover(flt):
    files = sorted(glob.glob(os.path.join(TESTS_DIR, "test_*.py")))
    if flt:
        files = [f for f in files if flt in os.path.basename(f)]
    return files


def run_module(path, env):
    name = os.path.basename(path)
    print(f"\n\033[1;35m{'=' * 60}\n  {name}\n{'=' * 60}\033[0m")
    try:
        p = subprocess.run([sys.executable, path], env=env, text=True,
                           capture_output=True, timeout=900)
    except subprocess.TimeoutExpired as exc:
        stdout = exc.stdout.decode(errors="replace") if isinstance(exc.stdout, bytes) else (exc.stdout or "")
        stderr = exc.stderr.decode(errors="replace") if isinstance(exc.stderr, bytes) else (exc.stderr or "")
        sys.stdout.write(stdout)
        sys.stderr.write(stderr)
        return {
            "name": name, "status": "FAIL", "pass": 0, "fail": 1,
            "rc": 124, "detail": "module timed out after 900 seconds",
        }
    except OSError as exc:
        return {
            "name": name, "status": "FAIL", "pass": 0, "fail": 1,
            "rc": 126, "detail": f"could not start module: {exc}",
        }
    sys.stdout.write(p.stdout)
    if p.stderr.strip():
        sys.stderr.write(p.stderr)
    output_lines = [line.strip() for line in p.stdout.splitlines() if line.strip()]
    m = RESULT_RE.fullmatch(output_lines[-1]) if output_lines else None
    pass_n = int(m.group(1)) if m else 0
    fail_n = int(m.group(2)) if m else 0
    skip_n = int(m.group(3) or 0) if m else 0
    protocol_error = ""
    if not m:
        status = "FAIL"
        fail_n = max(fail_n, 1)
        protocol_error = "missing RESULT trailer"
    elif skip_n > 0:
        if p.returncode == 3 and fail_n == 0:
            status = "SKIP"
        else:
            status = "FAIL"
            fail_n = max(fail_n, 1)
            protocol_error = "skip result requires exit 3 and zero failed checks"
    elif p.returncode == 0 and fail_n == 0 and pass_n > 0:
        status = "PASS"
    else:
        status = "FAIL"
        fail_n = max(fail_n, 1)
        if p.returncode == 3:
            protocol_error = "exit 3 requires RESULT skip=1"
        elif p.returncode == 0 and pass_n == 0:
            protocol_error = "passing result requires at least one passed check"
    clean_stdout = ANSI_RE.sub("", p.stdout)
    failure_lines = [line.strip() for line in clean_stdout.splitlines() if "✗" in line]
    if status == "FAIL" and not failure_lines:
        clean_stderr = ANSI_RE.sub("", p.stderr).strip()
        fallback = clean_stderr or clean_stdout.strip()
        failure_lines = fallback.splitlines()[-5:]
    if protocol_error:
        failure_lines.append(protocol_error)
    detail = " / ".join(failure_lines[-4:])[:1200]
    return {
        "name": name, "status": status, "pass": pass_n, "fail": fail_n,
        "rc": p.returncode, "detail": detail,
    }


def write_checklist(results, target_desc):
    total_pass = sum(r["pass"] for r in results)
    total_fail = sum(r["fail"] for r in results)
    n_pass = sum(1 for r in results if r["status"] == "PASS")
    n_fail = sum(1 for r in results if r["status"] == "FAIL")
    n_skip = sum(1 for r in results if r["status"] == "SKIP")
    ts = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    icon = {"PASS": "✅", "FAIL": "❌", "SKIP": "⚠️"}
    lines = [
        "# Orva E2E Checklist",
        "",
        "> Generated by `test/e2e/run.py`. This is a living record — every run",
        "> overwrites it. When a module FAILs, fix the code or harden the test;",
        "> when you add a feature, add a module here.",
        "",
        f"- **Last run:** {ts}",
        f"- **Target:** {target_desc}",
        f"- **Modules:** {n_pass} passed, {n_fail} failed, {n_skip} skipped",
        f"- **Checks:** {total_pass} passed, {total_fail} failed",
        "",
        "| Module | Status | Checks (pass/fail) |",
        "|---|---|---|",
    ]
    for r in sorted(results, key=lambda x: x["name"]):
        lines.append(f"| `{r['name']}` | {icon.get(r['status'], '?')} {r['status']} | {r['pass']}/{r['fail']} |")
    lines.append("")
    failed = [r for r in results if r["status"] == "FAIL"]
    if failed:
        lines.extend(["## Failure details", ""])
        for r in sorted(failed, key=lambda x: x["name"]):
            detail = r.get("detail") or f"module exited {r['rc']} without failure output"
            lines.append(f"- `{r['name']}`: {detail}")
        lines.append("")
    with open(os.path.join(HERE, "CHECKLIST.md"), "w") as f:
        f.write("\n".join(lines))
    return n_fail


def resolve_admin_key():
    key = os.environ.get("ORVA_API_KEY", "")
    if key:
        return key
    # Bare-metal host install location (read via sudo if needed).
    for cmd in (["cat", "/var/lib/orva/.admin-key"], ["sudo", "cat", "/var/lib/orva/.admin-key"]):
        try:
            p = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
            if p.returncode == 0 and p.stdout.strip():
                return p.stdout.strip()
        except Exception:
            pass
    return ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rebuild", action="store_true")
    ap.add_argument("--keep", action="store_true")
    ap.add_argument("--filter", default="")
    ap.add_argument("--url", default="")
    ap.add_argument("--api-key", default="")
    args = ap.parse_args()

    env = dict(os.environ)
    env["PYTHONPATH"] = HERE + os.pathsep + env.get("PYTHONPATH", "")
    env["MOCK_PORT"] = env.get("MOCK_PORT", "11434")
    env["MOCK_BIND"] = "0.0.0.0"
    env.setdefault("ORVA_BIN", os.path.join(HERE, "..", "..", "build", "orva"))

    inst = None
    if args.url:
        target = args.url.rstrip("/")
        env["ORVA_URL"] = target
        env["ORVA_API_KEY"] = args.api_key or resolve_admin_key()
        env["MOCK_HOST"] = "127.0.0.1"
        target_desc = f"external instance {target}"
    else:
        import env as envmod
        if not envmod.docker_available():
            print("docker is not available — use --url to target an existing instance", file=sys.stderr)
            return 2
        envmod.ensure_image(rebuild=args.rebuild)
        inst = envmod.Instance().start()
        try:
            inst.wait_healthy()
            env["ORVA_URL"] = inst.base_url
            env["ORVA_API_KEY"] = inst.admin_key()
            env["MOCK_HOST"] = "host.docker.internal"
            target_desc = f"isolated Docker image `{envmod.IMAGE}` ({inst.base_url})"
        except Exception as e:
            print(f"failed to bring up isolated instance: {e}", file=sys.stderr)
            inst.stop()
            return 2

    try:
        files = discover(args.filter)
        if not files:
            print("no test modules found in tests/", file=sys.stderr)
            return 2
        results = [run_module(f, env) for f in files]
        n_fail = write_checklist(results, target_desc)
        print(f"\n{'=' * 60}")
        for r in sorted(results, key=lambda x: x["name"]):
            print(f"  {r['status']:5} {r['name']}  ({r['pass']}/{r['fail']})")
        print(f"{'=' * 60}")
        print(f"CHECKLIST.md written. {n_fail} module(s) failed.")
        return 1 if n_fail else 0
    finally:
        if inst and not args.keep:
            inst.stop()
        elif inst:
            print(f"[env] kept running: {inst.base_url} (docker rm -f {inst.name} to remove)")


if __name__ == "__main__":
    sys.exit(main())
