package firewall

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

// Default resolvers used when system_config.dns_servers is unset OR
// empty. Cloudflare + Google — both have IPv6 fallback, both are
// authless and globally available.
var DefaultDNSServers = []string{"1.1.1.1", "8.8.8.8"}

// ResolvConfPath returns the on-disk path of the generated resolv.conf
// that egress sandboxes bind-mount as /etc/resolv.conf. We write it
// next to the firewall state so operators can inspect it without
// digging into Docker volumes.
func ResolvConfPath(dataDir string) string {
	return filepath.Join(dataDir, "firewall", "resolv.conf")
}

// HostsFilePath returns the on-disk path of the generated /etc/hosts
// override file. Operator-defined host→IP mappings are written here and
// bind-mounted into egress sandboxes so they take precedence over any
// upstream DNS resolution.
func HostsFilePath(dataDir string) string {
	return filepath.Join(dataDir, "firewall", "hosts")
}

// DNSRecord is a single host→IP override. Multiple records may share an
// IP; multiple hosts may share an IP (a single line will be written per
// record so it's reproducible). Stored serialised as "<host> <ip>" lines
// in the system_config.dns_records value.
type DNSRecord struct {
	Host string `json:"host"`
	IP   string `json:"ip"`
}

// DNSConfig is the operator-managed DNS settings rendered into the
// per-sandbox resolv.conf + hosts file and exposed through the API.
type DNSConfig struct {
	Servers []string    `json:"servers"` // resolved IPs (v4 or v6)
	Search  string      `json:"search"`  // optional DNS search domain
	Records []DNSRecord `json:"records"` // host→IP overrides (beats DNS)
	// Defaults exposed to the UI so it can show a "reset to default" hint.
	Defaults []string `json:"defaults"`
}

// LoadDNSConfig reads operator settings from system_config.
func LoadDNSConfig(db dbReader) DNSConfig {
	raw := strings.TrimSpace(db.GetSystemConfigString("dns_servers", ""))
	servers := []string{}
	if raw != "" {
		for _, s := range strings.Split(raw, ",") {
			s = strings.TrimSpace(s)
			if s != "" && net.ParseIP(s) != nil {
				servers = append(servers, s)
			}
		}
	}
	return DNSConfig{
		Servers:  servers,
		Search:   strings.TrimSpace(db.GetSystemConfigString("dns_search", "")),
		Records:  parseDNSRecords(db.GetSystemConfigString("dns_records", "")),
		Defaults: append([]string(nil), DefaultDNSServers...),
	}
}

// parseDNSRecords decodes the on-disk "host ip" lines into structured
// records. Any line whose IP doesn't parse is dropped silently — the
// PUT handler validates strictly so this only matters if the raw config
// row was hand-edited.
func parseDNSRecords(raw string) []DNSRecord {
	if strings.TrimSpace(raw) == "" {
		return nil
	}
	out := []DNSRecord{}
	for _, line := range strings.Split(raw, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 {
			continue
		}
		host, ip := fields[0], fields[1]
		if net.ParseIP(ip) == nil {
			continue
		}
		out = append(out, DNSRecord{Host: host, IP: ip})
	}
	return out
}

// SerializeDNSRecords renders records into the storage format. Public so
// the API handler can persist its validated input the same way LoadDNSConfig
// reads it.
func SerializeDNSRecords(records []DNSRecord) string {
	var b strings.Builder
	for _, r := range records {
		fmt.Fprintf(&b, "%s %s\n", r.Host, r.IP)
	}
	return b.String()
}

// dbReader is the small subset of *database.Database the dns layer
// needs. Keeping it as an interface lets tests stub it without pulling
// in the whole DB.
type dbReader interface {
	GetSystemConfigString(key, fallback string) string
}

// WriteResolvConf renders the resolv.conf file the sandbox bind-mounts.
// Falls back to DefaultDNSServers when the operator has cleared the
// list — we never want to leave a sandbox with no resolver, since
// without DNS a function with network_mode=egress is half-broken.
//
// File is written atomically: temp + rename. Same content + same mode
// is a no-op (we still rewrite for simplicity; nstun reads on each
// spawn so there's no hot-reload race).
func WriteResolvConf(dataDir string, cfg DNSConfig) error {
	servers := cfg.Servers
	if len(servers) == 0 {
		servers = DefaultDNSServers
	}

	var b strings.Builder
	b.WriteString("# Generated by orva firewall manager. Edit DNS via the\n")
	b.WriteString("# Firewall page in the UI or PUT /api/v1/firewall/dns.\n")
	if cfg.Search != "" {
		fmt.Fprintf(&b, "search %s\n", cfg.Search)
	}
	for _, s := range servers {
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}
	b.WriteString("options edns0 timeout:2 attempts:2\n")

	target := ResolvConfPath(dataDir)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	tmp := target + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, target)
}

// WriteHostsFile renders the operator's host→IP overrides into a
// /etc/hosts-format file egress sandboxes bind-mount at /etc/hosts. The
// glibc/musl resolver consults files before DNS by default, so any record
// here wins over upstream resolution — exactly the override contract the
// UI promises.
//
// We always write a baseline localhost block so the in-sandbox resolver
// behaves sanely even if the operator clears their custom records.
func WriteHostsFile(dataDir string, records []DNSRecord) error {
	var b strings.Builder
	b.WriteString("# Generated by orva firewall manager. Edit DNS records via\n")
	b.WriteString("# the Firewall page in the UI or PUT /api/v1/firewall/dns.\n")
	b.WriteString("# Operator-defined entries below override any upstream DNS.\n\n")
	b.WriteString("127.0.0.1   localhost\n")
	b.WriteString("::1         localhost ip6-localhost ip6-loopback\n")
	if len(records) > 0 {
		b.WriteString("\n# Custom records\n")
		for _, r := range records {
			fmt.Fprintf(&b, "%s   %s\n", r.IP, r.Host)
		}
	}

	target := HostsFilePath(dataDir)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	tmp := target + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, target)
}
