package firewall

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strings"
)

// Default resolvers used when system_config.dns_servers is unset OR
// empty. Cloudflare + Google — both have IPv6 fallback, both are
// authless and globally available.
var DefaultDNSServers = []string{"1.1.1.1", "8.8.8.8"}

// ResolvConfPath returns the on-disk path of the generated resolv.conf
// that egress sandboxes bind-mount as /etc/resolv.conf. We write it
// next to the firewall state so operators can inspect it without
// digging into Docker volumes.
func ResolvConfPath(dataDir string) string {
	return filepath.Join(dataDir, "firewall", "resolv.conf")
}

// DNSConfig is the operator-managed DNS settings rendered into the
// per-sandbox resolv.conf and exposed through the API.
type DNSConfig struct {
	Servers []string `json:"servers"` // resolved IPs (v4 or v6)
	Search  string   `json:"search"`  // optional DNS search domain
	// Defaults exposed to the UI so it can show a "reset to default" hint.
	Defaults []string `json:"defaults"`
}

// LoadDNSConfig reads operator settings from system_config.
func LoadDNSConfig(db dbReader) DNSConfig {
	raw := strings.TrimSpace(db.GetSystemConfigString("dns_servers", ""))
	servers := []string{}
	if raw != "" {
		for _, s := range strings.Split(raw, ",") {
			s = strings.TrimSpace(s)
			if s != "" && net.ParseIP(s) != nil {
				servers = append(servers, s)
			}
		}
	}
	return DNSConfig{
		Servers:  servers,
		Search:   strings.TrimSpace(db.GetSystemConfigString("dns_search", "")),
		Defaults: append([]string(nil), DefaultDNSServers...),
	}
}

// dbReader is the small subset of *database.Database the dns layer
// needs. Keeping it as an interface lets tests stub it without pulling
// in the whole DB.
type dbReader interface {
	GetSystemConfigString(key, fallback string) string
}

// WriteResolvConf renders the resolv.conf file the sandbox bind-mounts.
// Falls back to DefaultDNSServers when the operator has cleared the
// list — we never want to leave a sandbox with no resolver, since
// without DNS a function with network_mode=egress is half-broken.
//
// File is written atomically: temp + rename. Same content + same mode
// is a no-op (we still rewrite for simplicity; nstun reads on each
// spawn so there's no hot-reload race).
func WriteResolvConf(dataDir string, cfg DNSConfig) error {
	servers := cfg.Servers
	if len(servers) == 0 {
		servers = DefaultDNSServers
	}

	var b strings.Builder
	b.WriteString("# Generated by orva firewall manager. Edit DNS via the\n")
	b.WriteString("# Firewall page in the UI or PUT /api/v1/firewall/dns.\n")
	if cfg.Search != "" {
		fmt.Fprintf(&b, "search %s\n", cfg.Search)
	}
	for _, s := range servers {
		fmt.Fprintf(&b, "nameserver %s\n", s)
	}
	b.WriteString("options edns0 timeout:2 attempts:2\n")

	target := ResolvConfPath(dataDir)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	tmp := target + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, target)
}
